name: srtx_parser
version: 2.0.1
description: A cross-platform, .srtx parser that allows you to read a String containing Html and Coordinates and results to subtitle objects.
homepage: https://github.com/ConferreAI/srtx_parser.git
repository: https://github.com/ConferreAI/srtx_parser.git
publish_to: "none"

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  collection: ^1.17.1
  csslib: ^0.17.2
  meta: ^1.8.0

dev_dependencies:
  test: ^1.23.1
